G4\Inventory\InventoryBundle\Entity\Condiciones:
    type: entity
    table: null
    repositoryClass: G4\Inventory\InventoryBundle\Entity\CondicionesRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: 255
    lifecycleCallbacks: {  }
